# Generated by Django 3.2 on 2021-05-01 20:26

import apps.account.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='driver', serialize=False, to='account.user')),
                ('national_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('busy', 'busy'), ('toward_the_passenger', 'toward_the_passenger')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
            managers=[
                ('objects', apps.account.managers.UserManager()),
            ],
        ),
    ]
