# Generated by Django 3.2 on 2021-05-02 13:55

import apps.account.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='driver',
            managers=[
                ('random', django.db.models.manager.Manager()),
                ('objects', apps.account.managers.UserManager()),
            ],
        ),
    ]
