# Generated by Django 3.2 on 2021-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('busy', 'busy'), ('toward_the_passenger', 'toward_the_passenger')], default='waiting', max_length=20),
        ),
    ]
